version: '1'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: table_booking_db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/table_booking_db
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "pass"

volumes:
  postgres_data:
